// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQ4rkMGWbZYBB3xdm_rjv_4hX6W3oFio',
    appId: '1:230760623326:web:6b26289031958b381f664f',
    messagingSenderId: '230760623326',
    projectId: 'vision-share-64644',
    authDomain: 'vision-share-64644.firebaseapp.com',
    storageBucket: 'vision-share-64644.firebasestorage.app',
    measurementId: 'G-ZLWQLE1ERY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlvI1x3CtNSerBX_jX1__TwlhopfG6IE',
    appId: '1:230760623326:android:7866cba1c8c44d531f664f',
    messagingSenderId: '230760623326',
    projectId: 'vision-share-64644',
    storageBucket: 'vision-share-64644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMuGtPzyp8SRXAqxlr24ssqtA-0K2-re8',
    appId: '1:230760623326:ios:5f7d4dc7755af7d81f664f',
    messagingSenderId: '230760623326',
    projectId: 'vision-share-64644',
    storageBucket: 'vision-share-64644.firebasestorage.app',
    iosBundleId: 'com.example.visionShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMuGtPzyp8SRXAqxlr24ssqtA-0K2-re8',
    appId: '1:230760623326:ios:5f7d4dc7755af7d81f664f',
    messagingSenderId: '230760623326',
    projectId: 'vision-share-64644',
    storageBucket: 'vision-share-64644.firebasestorage.app',
    iosBundleId: 'com.example.visionShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQ4rkMGWbZYBB3xdm_rjv_4hX6W3oFio',
    appId: '1:230760623326:web:9fe4d8c0060261961f664f',
    messagingSenderId: '230760623326',
    projectId: 'vision-share-64644',
    authDomain: 'vision-share-64644.firebaseapp.com',
    storageBucket: 'vision-share-64644.firebasestorage.app',
    measurementId: 'G-XNR9NSS5EK',
  );
}
